# Generated by Django 5.0.7 on 2024-08-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book_author_book_is_bestseller_alter_book_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_bestseller',
            new_name='is_bestselling',
        ),
    ]
